### ISSUE TITLE
BitNami Jruby stack

### ISSUE THREAD

**Issue by DouglasAllen** [jruby/jruby-lint#12]
Will jruby-lint install on this stack? If so how do we do it? Perhaps get with them to include it. Nokogiri has a java version. Maybe that one should be specified in the gemspec.
http://bitnami.com/stack/jruby

There needs to be a bat file for windows to run it then.

**Comment by enebo** [comment]
This is ancient but I tested last version of release jruby-lint (which is broken to soon be fixed) but it does launch for me on windows.  If there is a missing binstub for windows on bitnami this was either a) a mistake on packaging of the stack b) some binstub generation issue with jruby or rubygems which has since been fixed.
